"""
extractors/bill_extractor.py
============================
Builds a Bedrock Claude prompt from Textract output to extract
hospital bill payment fields via semantic understanding.
No regex or Comprehend — Claude interprets any label variation.

Output schema
-------------
{
  "billNo":          str,   # e.g. "BILL-79780"
  "totalBillAmount": str,   # e.g. "₹108599"
  "amountToBePayed": str,   # e.g. "₹34956"  (patient's share; equals totalBillAmount when no insurance)
  "description":     str,   # Markdown payment summary generated by Bedrock
}
"""

from __future__ import annotations

import json
import logging
from typing import Any

import bedrock_utils

logger = logging.getLogger(__name__)

_PROMPT_TEMPLATE = """\
You are a medical billing document parser.

Below is text and key-value pairs extracted from a hospital bill using OCR.

RAW TEXT:
{raw_text}

KEY-VALUE PAIRS:
{key_values}

Extract exactly these fields and return ONLY valid JSON with no explanation:
{{
  "billNo":          "bill or invoice identifier (e.g. BILL-79780)",
  "totalBillAmount": "total amount including all charges (e.g. ₹108599)",
  "amountToBePayed": "amount the patient must pay after insurance deduction (e.g. ₹34956)"
}}

Rules:
- Preserve the ₹ symbol in all amount fields
- Remove commas from numbers (₹1,08,599 → ₹108599)
- Use "" for any field that cannot be found
- billNo labels: Bill No, Invoice No, Receipt No, Bill ID, Bill Number, etc.
- totalBillAmount labels: Total, Grand Total, Gross Amount, Total Bill, Total Charges, Sub Total+GST, etc.
- amountToBePayed labels: Balance Due, Net Payable, Amount Due, Patient Share,
  Outstanding, Amount Payable, Patient Responsibility, Patient Liability, Co-pay, etc.
  IMPORTANT: If no patient-specific payable amount exists (i.e. no insurance deduction
  is shown), use the Grand Total / Total amount as amountToBePayed — the patient pays
  the full bill.
"""

_DESCRIPTION_PROMPT_TEMPLATE = """\
You are a medical billing assistant.

Below is the full text extracted from a hospital bill.

RAW TEXT:
{raw_text}

KEY-VALUE PAIRS (structured fields):
{key_values}

CHARGE TABLE:
{tables}

Generate a concise Markdown payment summary using ONLY the information present above.

Format requirements:
- Start with "## Payment Summary"
- Include the bill number, hospital name, patient name, and admission/discharge dates if present
- List each charge line as: **Charge Name**: ₹amount
- Show Sub Total, GST (if any), and Grand Total prominently
- End with a one-line note of the total amount the patient owes
- Do NOT invent or assume any values not present in the text
- Return ONLY the Markdown, no preamble or disclaimer
"""


def extract_payment(textract_result: dict[str, Any]) -> dict[str, str]:
    """
    Use Bedrock Claude to semantically extract payment fields from Textract output
    and generate a Markdown payment description from the raw bill text.

    Parameters
    ----------
    textract_result : output of textract_utils.extract_document()

    Returns
    -------
    payment dict with billNo, totalBillAmount, amountToBePayed, description.
    """
    raw_text   = textract_result.get("raw_text", "")
    key_values = textract_result.get("key_values", {})
    tables     = textract_result.get("tables", [])

    # ── 1. Extract structured payment fields ─────────────────────────────
    extraction_prompt = _PROMPT_TEMPLATE.format(
        raw_text   = raw_text,
        key_values = json.dumps(key_values, indent=2, ensure_ascii=False),
    )
    result = bedrock_utils.extract_structured_fields(extraction_prompt)

    bill_no           = result.get("billNo",          "")
    total_bill_amount = result.get("totalBillAmount", "")
    amount_to_be_paid = result.get("amountToBePayed", "")

    # Fallback: when no patient-specific payable is found (no insurance),
    # the patient owes the full bill — use totalBillAmount.
    if not amount_to_be_paid and total_bill_amount:
        amount_to_be_paid = total_bill_amount
        logger.info(
            "amountToBePayed not found in bill — defaulting to totalBillAmount: %s",
            total_bill_amount,
        )

    # ── 2. Generate Markdown description from raw Textract data ───────────
    # Format tables as a readable string for the prompt
    table_str = "\n".join(
        "  |  ".join(str(cell) for cell in row)
        for row in tables
    ) if tables else "(no table data)"

    description_prompt = _DESCRIPTION_PROMPT_TEMPLATE.format(
        raw_text   = raw_text,
        key_values = json.dumps(key_values, indent=2, ensure_ascii=False),
        tables     = table_str,
    )
    description = bedrock_utils.generate_text(description_prompt)

    payment = {
        "billNo":          bill_no,
        "totalBillAmount": total_bill_amount,
        "amountToBePayed": amount_to_be_paid,
        "description":     description,
    }

    logger.info("Extracted payment: %s", {k: v[:60] if k == "description" else v for k, v in payment.items()})
    return payment
