import React from "react"
import { SafeAreaView, StyleSheet } from "react-native"

import { Amplify } from "aws-amplify"
import { Authenticator } from "@aws-amplify/ui-react-native"

// amplify_outputs.json is generated by `npx ampx sandbox` or `npx ampx generate outputs`
// It is gitignored — each developer generates their own via sandbox.
import outputs from "./amplify_outputs.json"
import { HomeScreen } from "./src/screens/HomeScreen"

Amplify.configure(outputs)

export default function App() {
  return (
    <Authenticator.Provider>
      {/*
        Authenticator renders the hosted login/signup UI automatically.
        Children are only shown when the user is signed in.
      */}
      <Authenticator>
        <SafeAreaView style={styles.container}>
          <HomeScreen />
        </SafeAreaView>
      </Authenticator>
    </Authenticator.Provider>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5"
  }
})
